---
- name: Instalar libselinux-python
  yum: name=libselinux-python state=present  
  
- name: Instalar nginx para CentOS 7
  yum: name=nginx state=latest

- name: Copiar el archivo de nginx default.conf
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
      
- name: Copiar el archivo nginx-cent.conf
  template: 
    src: nginx-cent.conf
    dest: /etc/nginx/nginx.conf
      
- name: Copiar index.php para phpinfo
  copy:
    src: index.php
    dest: /var/www/html/
  
# Habilita y inicia el servicio de nginx
- name: start nginx
  service: name=nginx state=started enabled=true